"""CLine46 の物理配置とキーマップ(リポジトリの初期値)から表示用の src/layout.ts を作る。"""
import json, re, sys, pathlib

root = pathlib.Path(sys.argv[1])
dtsi = (root / "boards/shields/CLine46/CLine46.dtsi").read_text()
keys = [tuple(int(v) for v in m) for m in re.findall(
    r"&key_physical_attrs\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)", dtsi)]

km = (root / "config/CLine46.keymap").read_text()
km = re.sub(r"//[^\n]*", "", km)
km = re.sub(r"/\*.*?\*/", "", km, flags=re.S)
body = km[km.index("compatible = \"zmk,keymap\""):]
layers = []
for m in re.finditer(r"(\w+)\s*\{([^{}]*?)bindings\s*=\s*<(.*?)>;", body, re.S):
    name, pre, binds = m.group(1), m.group(2), m.group(3)
    dn = re.search(r'display-name\s*=\s*"([^"]*)"', pre)
    toks = [t.split() for t in ("&" + b for b in binds.split("&")[1:])]
    layers.append({"name": dn.group(1) if dn else name, "bindings": [" ".join(t) for t in toks]})

KEYS = {"LSHIFT": "Shift", "RSHIFT": "Shift", "LCTRL": "Ctrl", "RCTRL": "Ctrl", "LALT": "Alt",
        "RALT": "Alt", "LGUI": "Win", "RGUI": "Win", "SPACE": "Space", "BSPC": "BS", "RET": "Enter",
        "ESC": "Esc", "DEL": "Del", "TAB": "Tab", "MINUS": "-", "COMMA": ",", "DOT": ".",
        "SLASH": "/", "SEMI": ";", "COLON": ":", "LPAR": "(", "RPAR": ")", "AT": "@", "EXCL": "!",
        "EQUAL": "=", "CARET": "^", "PIPE": "|", "SQT": "'", "DQT": "\"", "LBKT": "[", "RBKT": "]",
        "HASH": "#", "PRCNT": "%", "PLUS": "+", "TILDE": "~", "BSLH": "\\", "GRAVE": "`",
        "LBRC": "{", "RBRC": "}", "AMPS": "&", "STAR": "*", "DLLR": "$", "LANG1": "かな",
        "LANG2": "英数", "C_AC_SEARCH": "🔍", "PG_UP": "PgUp", "PG_DN": "PgDn", "UP": "↑",
        "DOWN": "↓", "LEFT": "←", "RIGHT": "→", "HOME": "Home", "END": "End", "PSCRN": "PrtSc",
        "CAPS": "Caps", "C_VOL_UP": "Vol+", "C_VOL_DN": "Vol-", "C_MUTE": "Mute", "C_PP": "⏯",
        "C_PREV": "⏮", "C_NEXT": "⏭", "C_STOP": "⏹", "C_REWIND": "⏪", "C_FF": "⏩"}
MODS = {"LC": "Ctrl", "RC": "Ctrl", "LS": "Shift", "RS": "Shift", "LA": "Alt", "RA": "Alt",
        "LG": "Win", "RG": "Win"}

def key(k):
    mods = []
    while (m := re.match(r"(L[CSAG]|R[CSAG])\((.*)\)$", k)):
        mods.append(MODS[m.group(1)]); k = m.group(2)
    k = KEYS.get(k, re.sub(r"^N(\d)$", r"\1", k))
    return "+".join(mods + [k])

def label(b):
    t = b.split()
    n, a = t[0][1:], t[1:]
    if n == "kp": return key(a[0])
    if n == "trans": return "▽"
    if n == "none": return "×"
    if n == "lt": return f"{key(a[1])}/L{a[0]}"
    if n in ("mo", "to", "tog", "sl"): return f"{n} {a[0]}"
    if n == "mt": return f"{key(a[1])}/{key(a[0])}"
    if n == "mkp": return {"LCLK": "左クリック", "RCLK": "右クリック", "MCLK": "中クリック",
                           "MB4": "戻る", "MB5": "進む"}.get(a[0], a[0])
    special = {"app_tab": "App切替", "dbl_click": "ダブルクリック", "studio_unlock": "Studio Unlock",
               "bootloader": "書込モード", "os_win": "Winモード", "os_mac": "Macモード",
               "ind_con": "接続LED", "ind_bat": "電池LED", "mac_dictation": "音声入力",
               "mac_up": "↑", "mac_down": "↓", "mac_left": "←", "mac_right": "→", "mac_home": "Home",
               "mac_end": "End", "mac_bspc": "BS", "mac_del": "Del", "mac_f4": "F4"}
    if n in special: return special[n]
    if n == "mod_click": return f"{key(a[0])}+クリック"
    if n == "out": return "USB/BT切替"
    if n == "bt": return " ".join(a).replace("BT_SEL", "BT").replace("BT_", "BT ")
    return " ".join([n] + a)

NAMES = ["L0 基本", "L1 記号・数字", "L2 ナビ", "L3 設定", "L4 Fn・メディア", "L5 ウィンドウ",
         "L6 マウス", "L7 Mac", "L8 Mac ナビ", "L9 Mac Fn", "L10 Mac ウィンドウ", "L11 Mac 設定",
         "L12 Mac マウス", "L13 Mac 記号"]

def layer_labels(i, l):
    labels = [label(b) for b in l["bindings"]]
    # Mac 用レイヤーでは GUI は ⌘
    return [x.replace("Win", "⌘") for x in labels] if i >= 7 else labels

out = {"keys": [{"x": x, "y": y, "w": w, "h": h} for (w, h, x, y) in keys],
       "layers": [{"name": NAMES[i] if i < len(NAMES) else l["name"], "labels": layer_labels(i, l)}
                   for i, l in enumerate(layers)]}
assert all(len(l["labels"]) == len(keys) for l in out["layers"]), [len(l["labels"]) for l in out["layers"]]
print("// Generated by scripts/gen_layout.py from the repository keymap. Do not edit.")
print("export const LAYOUT = " + json.dumps(out, ensure_ascii=False, indent=1) + " as const;")
